"""add Comment model

Revision ID: 081738079855
Revises: 4078ba02e2db
Create Date: 2025-07-12 12:28:03.666530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081738079855'
down_revision = '4078ba02e2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'answer_id', name='unique_user_answer_vote')
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_answer_vote', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_answer_vote', ['user_id', 'answer_id'])

    op.drop_table('comment')
    # ### end Alembic commands ###
