"""Enhance Notification model for notification system

Revision ID: 3e8596977cd8
Revises: 283e9eb46412
Create Date: 2025-07-12 11:58:16.466443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8596977cd8'
down_revision = '283e9eb46412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('related_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('related_id')
        batch_op.drop_column('url')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
