"""Add moderation and banning fields

Revision ID: 4078ba02e2db
Revises: 3e8596977cd8
Create Date: 2025-07-12 12:01:15.226041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4078ba02e2db'
down_revision = '3e8596977cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
