"""add user bio, avatar, reputation

Revision ID: f20049f6bc59
Revises: 081738079855
Create Date: 2025-07-12 12:31:54.581329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20049f6bc59'
down_revision = '081738079855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reputation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reputation')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
